jms_serializer:
    visitors:
        xml:
            format_output: '%kernel.debug%'
    metadata:
        auto_detection: false
        directories:
            app:
                namespace_prefix: "App\\Domain"
                path: '%kernel.project_dir%/src/Application/Resources/serializer'
