version: "2"
services:
 nginx:
   build: ./docker/nginx
   depends_on:
    - php-fpm
   links:
    - php-fpm
   environment:
    - NGINX_PORT=80
    - FASTCGI_HOST=php-fpm
    - FASTCGI_PORT=9000
    - DOCUMENT_ROOT=/usr/local/src/app/public
    - SERVER_NAME=localhost
   ports:
    - 8002:80
   volumes:
    - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./docker/nginx/templates/default.conf.template:/etc/nginx/conf.d/default.conf.template
    - ./docker/nginx/entrypoint.sh:/entrypoint.sh
   volumes_from:
    - php-fpm
   command: "/bin/bash /entrypoint.sh"

 database:
   image: postgres:9.6
   ports:
    - 5439:5432
   volumes:
    - data:/var/lib/postgresql/data
   environment:
     POSTGRES_PASSWORD: E1uoLAjHWHza2k9j
     POSTGRES_USER: app
     POSTGRES_DB: app

 php-fpm:
   image: dmiseev/php-fpm7.1
   depends_on:
    - database
   links:
    - database
   volumes:
    - .:/usr/local/src/app
   working_dir: /usr/local/src/app
   extra_hosts:
    - "app:127.0.0.1"
   environment:
    - APP_ENV=dev
    - APP_DEBUG=1
    - APP_SECRET=83512d52ee87s97e6e9dge2322dc7eqq81885
    - DATABASE_HOST=database
    - DATABASE_USER=app
    - DATABASE_PASSWORD=E1uoLAjHWHza2k9j
    - DATABASE_NAME=app
    - DATABASE_PORT=5432

volumes:
  data: {}