# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'

services:

    App\Infrastructure\Domain\Doctrine\DoctrineUserRepository:
        class: App\Infrastructure\Domain\Doctrine\DoctrineUserRepository
        arguments:
            $registry: '@doctrine'

    App\Domain\User\UserRepository: '@App\Infrastructure\Domain\Doctrine\DoctrineUserRepository'

#    App\Http\Controller\UserController:
#        public: true
#        arguments:
#            $userRepository: '@App\Domain\User\UserRepository'
#            $jwt: '@lexik_jwt_authentication.jwt_manager'

    App\Http\EventListener\DomainExceptionListener:
        class: App\Http\EventListener\DomainExceptionListener
        tags:
         - { name: kernel.event_listener, event: kernel.exception }