App\Domain\User\User:
  type: entity
  table: users

  id:
    id:
      type: integer
      generator:
        strategy: AUTO

  fields:
    name:
      type: string
      column: name
      length: 64
    email:
      type: string
      column: email
      length: 64
    deletedAt:
      type: datetimetz
      column: deleted_at
      nullable: true

  uniqueConstraints:
    search_idx:
      columns: [email, deleted_at]